fix chains signing-secrets public-key access     - Cosign by default creates immutable secrets, so we need delete     permissions in openshift-pipelines namespace over secrets     https://github.com/sigstore/cosign/blob/main/pkg/cosign/kubernetes/secret.go#L119C5-L119C14     - additional check to make sure public key is not empty.
Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>

diff --git a/operator/test/manifests/test/tekton-chains/public-key.yaml b/operator/test/manifests/test/tekton-chains/public-key.yaml
--- a/operator/test/manifests/test/tekton-chains/public-key.yaml
+++ b/operator/test/manifests/test/tekton-chains/public-key.yaml
@@ -19,5 +19,10 @@ spec:
                 set -o pipefail
                 set -x
                 PUBLIC_KEY=$(oc get secret public-key -n openshift-pipelines -o jsonpath='{.data.cosign\.pub}')
+                if [[ -z "$PUBLIC_KEY" ]]; then
+                  echo "[ERROR] Public key is empty."
+                  exit 1
+                fi
+                echo "Public key exists."
                 echo "$PUBLIC_KEY" | base64 -d
   serviceAccountName: chains-test
